import type { OkcEvent } from "./types";

// Curated fall 2026 listings. This is the source for supabase/seed.sql
// (run `npm run seed:generate`) and the fallback when Supabase isn't configured.
// Map pins are approximate; "Directions" links use the street address when there is one.

type Input = Partial<OkcEvent> & Pick<OkcEvent, "id" | "title" | "category">;

const e = (x: Input): OkcEvent => ({
  description: null,
  start_date: null,
  end_date: null,
  hours_text: null,
  venue: null,
  address: null,
  city: "Oklahoma City",
  lat: null,
  lng: null,
  price_text: null,
  is_free: false,
  url: null,
  image_url: null,
  tags: [],
  ...x,
});

const SCISSORTAIL = {
  venue: "Scissortail Park",
  address: "300 SW 7th St",
  lat: 35.461,
  lng: -97.519,
};

const PAYCOM = {
  venue: "Paycom Center",
  address: "100 W Reno Ave",
  lat: 35.4634,
  lng: -97.5151,
  url: "https://www.nba.com/thunder/schedule",
};

export const EVENTS: OkcEvent[] = [
  // --- Hispanic Heritage Month & Latino culture ---
  e({
    id: "fiestas-de-las-americas",
    title: "Fiestas de las Américas",
    description:
      "Parade from Scissortail Park south on Robinson to Calle Dos Cinco, followed by a festival in Historic Capitol Hill.",
    category: "festival",
    start_date: "2026-10-03",
    end_date: "2026-10-03",
    hours_text: "Parade 11 a.m.–1 p.m. · Festival 10 a.m.–7 p.m.",
    venue: "Historic Capitol Hill",
    address: "2512 S Harvey Ave",
    lat: 35.4388,
    lng: -97.5188,
    price_text: "Free",
    is_free: true,
    tags: ["hispanic-heritage", "parade", "music"],
  }),
  e({
    id: "dale-dale-dale",
    title: "Dale Dale Dale: The Art of the Piñata",
    description:
      "The piñata as sculpture, featuring Piñatas Aylin — Mexican artists Mayra Reza and Rafael Salinas — with traditional papier-mâché, layered paper, and hand-painted detail. Pair it with Sam Noble's \"Lives of the Dead\" for one Norman trip.",
    category: "art",
    end_date: "2026-11-01",
    venue: "Firehouse Art Center",
    address: "444 S Flood Ave",
    city: "Norman",
    lat: 35.2175,
    lng: -97.4527,
    tags: ["hispanic-heritage", "exhibition", "new"],
  }),
  e({
    id: "lives-of-the-dead",
    title: "\"Lives of the Dead\" Exhibition",
    description:
      "More than 1,000 years of Mexican and Latin American art: ofrendas, sugar skulls, contemporary paintings, and antique prints.",
    category: "art",
    end_date: "2027-01-31", // "through January"
    venue: "Sam Noble Museum",
    address: "2401 Chautauqua Ave",
    city: "Norman",
    lat: 35.1946,
    lng: -97.4481,
    price_text: "Free with museum admission",
    tags: ["hispanic-heritage", "dia-de-los-muertos", "exhibition"],
  }),
  e({
    id: "festival-de-vida-y-muerte",
    title: "OKC Festival de Vida y Muerte",
    description: "Day of the Dead celebration with a Catrina Contest.",
    category: "festival",
    start_date: "2026-11-01",
    end_date: "2026-11-01",
    ...SCISSORTAIL,
    tags: ["hispanic-heritage", "dia-de-los-muertos"],
  }),
  e({
    id: "scissortail-hispanic-festival",
    title: "Hispanic Festival at Scissortail Park",
    description: "The 2026 date hasn't been posted yet. Check scissortailpark.org before planning around it.",
    category: "festival",
    hours_text: "2026 date not yet posted",
    ...SCISSORTAIL,
    url: "https://scissortailpark.org",
    tags: ["hispanic-heritage"],
  }),

  // --- Fall festivals: September ---
  e({
    id: "oklahoma-state-fair",
    title: "Oklahoma State Fair",
    category: "festival",
    start_date: "2026-09-17",
    end_date: "2026-09-27",
    hours_text: "Ends Sunday",
    venue: "OKC Fairgrounds",
    address: "3001 General Pershing Blvd",
    lat: 35.479,
    lng: -97.569,
    tags: ["fall", "family"],
  }),
  e({
    id: "route-66-balloon-festival",
    title: "Route 66 Balloon Festival",
    category: "festival",
    start_date: "2026-09-23",
    end_date: "2026-09-27",
    city: "Arcadia",
    tags: ["fall", "family"],
  }),
  e({
    id: "plaza-district-festival",
    title: "Plaza District Festival",
    category: "festival",
    start_date: "2026-09-26",
    end_date: "2026-09-26",
    hours_text: "Noon–11 p.m.",
    venue: "Plaza District",
    address: "1700 NW 16th St",
    lat: 35.4866,
    lng: -97.5452,
    price_text: "Free",
    is_free: true,
    tags: ["fall", "music", "art"],
  }),
  e({
    id: "mesta-festa",
    title: "Mesta Festa",
    description:
      "31st annual. Kid-friendly with live music, family activities, sand volleyball, local artists, pop-up shops, and a beverage garden (samples require a purchased wristband).",
    category: "festival",
    start_date: "2026-09-27",
    end_date: "2026-09-27",
    hours_text: "Noon–6 p.m.",
    venue: "Perle Mesta Park",
    address: "NW 18th St & N Shartel Ave",
    lat: 35.489,
    lng: -97.5265,
    price_text: "Free",
    is_free: true,
    tags: ["fall", "family", "music", "new"],
  }),

  // --- October ---
  e({
    id: "pumpkinville",
    title: "Pumpkinville",
    category: "family",
    start_date: "2026-10-01",
    end_date: "2026-10-25",
    venue: "Myriad Botanical Gardens",
    address: "301 W Reno Ave",
    lat: 35.4655,
    lng: -97.5165,
    tags: ["fall", "family", "pumpkins"],
  }),
  e({
    id: "asian-night-market",
    title: "Asian Night Market Festival",
    category: "festival",
    start_date: "2026-10-02",
    end_date: "2026-10-03",
    price_text: "Free",
    is_free: true,
    tags: ["fall", "food"],
  }),
  e({
    id: "greek-fest-okc",
    title: "Greek Fest OKC",
    category: "festival",
    start_date: "2026-10-02",
    end_date: "2026-10-04",
    tags: ["fall", "food"],
  }),
  e({
    id: "wings-fall-festival",
    title: "Wings Fall Festival & Pumpkin Patch",
    category: "family",
    start_date: "2026-10-02",
    end_date: "2026-10-18",
    hours_text: "Weekends only",
    city: "Edmond",
    tags: ["fall", "family", "pumpkins"],
  }),
  e({
    id: "orr-family-farm",
    title: "Orr Family Farm Fall Festival",
    category: "family",
    end_date: "2026-11-14",
    hours_text: "Select dates",
    venue: "Orr Family Farm",
    address: "14400 S Western Ave",
    lat: 35.328,
    lng: -97.5304,
    tags: ["fall", "family", "pumpkins"],
  }),
  e({
    id: "norman-downtown-fall-festival",
    title: "Norman Downtown Fall Festival",
    category: "festival",
    start_date: "2026-10-23",
    end_date: "2026-10-23",
    venue: "Downtown Norman",
    address: "E Main St",
    city: "Norman",
    lat: 35.2208,
    lng: -97.4436,
    price_text: "Free",
    is_free: true,
    tags: ["fall"],
  }),
  e({
    id: "storybook-forest",
    title: "Storybook Forest",
    description:
      "No-scares alternative to trick-or-treating: a lit forest path past life-size storybook scenes, candy, campfires, a reading tent, carnival games, and a hayride. Buy tickets in advance (600 child tickets per night). Cash only on site; no pets or outside food.",
    category: "family",
    start_date: "2026-10-23",
    end_date: "2026-10-30",
    hours_text: "5:30–8:30 p.m. nightly",
    venue: "Arcadia Lake – Spring Creek Park",
    address: "7200 E 15th St",
    city: "Edmond",
    lat: 35.638,
    lng: -97.386,
    price_text: "$15 per child, $5 per adult",
    tags: ["fall", "family", "halloween", "new"],
  }),
  e({
    id: "okc-parks-halloween-harvest",
    title: "OKC Parks Halloween Harvest Festivals",
    category: "family",
    start_date: "2026-10-31",
    end_date: "2026-10-31",
    price_text: "Free",
    is_free: true,
    tags: ["fall", "family", "halloween"],
  }),

  // --- November ---
  e({
    id: "turkey-shoot-moore",
    title: "Turkey Shoot Free Throw Contest",
    description:
      "Shoot 10 free throws; the top shooter in each of six age divisions (5–8 up to 50+) wins a Thanksgiving turkey. Online registration required, closes 5 p.m. Nov. 10. One turkey per family.",
    category: "family",
    start_date: "2026-11-13",
    end_date: "2026-11-13",
    hours_text: "6–8 p.m.",
    venue: "The Station Recreation Center",
    address: "700 S Broadway St",
    city: "Moore",
    lat: 35.3288,
    lng: -97.486,
    price_text: "Free",
    is_free: true,
    tags: ["family", "sports", "new"],
  }),

  // --- Art exhibitions ---
  e({
    id: "art-nouveau-okcmoa",
    title: "\"The Triumph of Nature: Art Nouveau\"",
    category: "art",
    start_date: "2026-10-31",
    hours_text: "Opens Oct. 31",
    venue: "Oklahoma City Museum of Art",
    address: "415 Couch Dr",
    lat: 35.469,
    lng: -97.521,
    tags: ["exhibition"],
  }),

  // --- Thunder home games (Paycom Center) ---
  // Partial list. Confirm dates and tip times at nba.com/thunder/schedule.
  e({
    id: "thunder-2026-10-22-den",
    title: "Thunder vs. Denver Nuggets — Home Opener",
    category: "sports",
    start_date: "2026-10-22",
    end_date: "2026-10-22",
    hours_text: "8:30 p.m. tip",
    ...PAYCOM,
    tags: ["thunder", "basketball"],
  }),
  e({
    id: "thunder-2026-10-25-lac",
    title: "Thunder vs. LA Clippers",
    category: "sports",
    start_date: "2026-10-25",
    end_date: "2026-10-25",
    hours_text: "Check tip time",
    ...PAYCOM,
    tags: ["thunder", "basketball"],
  }),
  e({
    id: "thunder-2026-10-26-phx",
    title: "Thunder vs. Phoenix Suns",
    category: "sports",
    start_date: "2026-10-26",
    end_date: "2026-10-26",
    hours_text: "Check tip time",
    ...PAYCOM,
    tags: ["thunder", "basketball"],
  }),
  e({
    id: "thunder-2026-11-18-atl",
    title: "Thunder vs. Atlanta Hawks",
    category: "sports",
    start_date: "2026-11-18",
    end_date: "2026-11-18",
    hours_text: "Check tip time",
    ...PAYCOM,
    tags: ["thunder", "basketball"],
  }),
  e({
    id: "thunder-2026-11-20-nop",
    title: "Thunder vs. New Orleans Pelicans — NBA Cup",
    category: "sports",
    start_date: "2026-11-20",
    end_date: "2026-11-20",
    hours_text: "7 p.m. tip",
    ...PAYCOM,
    tags: ["thunder", "basketball", "nba-cup"],
  }),
  e({
    id: "thunder-2026-11-25-min",
    title: "Thunder vs. Minnesota Timberwolves — NBA Cup",
    category: "sports",
    start_date: "2026-11-25",
    end_date: "2026-11-25",
    hours_text: "6:30 p.m. tip",
    ...PAYCOM,
    tags: ["thunder", "basketball", "nba-cup"],
  }),
];
