// Regenerates supabase/seed.sql from src/lib/events-data.ts.
// Usage: npm run seed:generate
import { writeFileSync } from "node:fs";
import { EVENTS } from "../src/lib/events-data.ts";

const cols = [
  "title", "description", "category", "start_date", "end_date", "hours_text", "venue",
  "address", "city", "lat", "lng", "price_text", "is_free", "url", "tags",
];

const lit = (v) => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return `array[${v.map(lit).join(", ")}]::text[]`;
  return `'${String(v).replaceAll("'", "''")}'`;
};

const rows = EVENTS.map((e) => `  (${cols.map((c) => lit(e[c])).join(", ")})`);
const sql = `-- Generated by scripts/generate-seed.mjs from src/lib/events-data.ts. Do not edit by hand.
delete from public.events;

insert into public.events (${cols.join(", ")}) values
${rows.join(",\n")};
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`Wrote ${EVENTS.length} events to supabase/seed.sql`);
